language: node_js
node_js:
  - "11.14.0"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- ng build --prod
deploy:
  provider: pages
  skip_cleanup: true
  target_branch: gh-pages
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master