language: node_js
node_js:
  - "11.14.0"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- ng build --prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "141fd567e0ccca84a7d4b25b6035670141c100dc"
  keep_history: true
  on:
    branch: master